{% set name = "emoji" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e42da4f8d648f8ef10691bc246f682a1ec6b18373abfd9be10ec0b398823bd11

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - emoji

about:
  home: https://github.com/carpedm20/emoji/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Emoji for Python

  dev_url: https://github.com/carpedm20/emoji/

extra:
  recipe-maintainers:
    - synapticarbors
