{% set name = "emoji" %}
{% set version = "2.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2986c21e4aba6b9870df40ef487a17be863cb7778dcf1c01e25917b7cd210bb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - emoji

about:
  home: https://github.com/carpedm20/emoji/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Emoji for Python
  description: |
    The main purpose of this package is converting Unicode emoji to emoji names and vice versa with emojize() and
    demojize().
  doc_url: https://carpedm20.github.io/emoji/docs/
  dev_url: https://github.com/carpedm20/emoji/

extra:
  recipe-maintainers:
    - synapticarbors
