travis:
  secure:
    BINSTAR_TOKEN: 1CZOMBX5pJD138j3tCPnYv+21AygqxmzTuew22lu+GxrTPEnxNQaugXuWkJPtZFs/LejKSUjeeVjEp3BrumJf/A6oOSDNR98Mi0Y520+QS/e1ivdBxMYQm906X0Z9IuWZj4CQvDNXcY7aoVLtM0nhbEAyn3Rvfj7mt+ecVN1lbim9dtzRSPV+HhvUdyOBZiFbRL+5itwxiuvzV69Et12ZDdJX8KD4vYiZSm19CnpJRupyH4TZj2QhRDVK+fo2qnVNfIV2urj9Z7nD4DXuIK2JWO9lCiFOQfacYCJ90SvJ87j0r6jcm58H6IjsBJaSn2TQFcZLpbAtJTSeUbUEv1Yb+NaGpxVSA6yOFM6oOgwu5YehpOSoYyOkVwFMKNIGMZbwv3oSbYIxoFVomcaqfG0BUomrvmsIy6yPsjdGQNdL7QsdlfQ8eSjTvVOGR+Oruk6LHgE6sI3C7OdlJ0PcF8vzp+Hsk6NSkHEcwaiUm+Ss8bWpHxT2aGKQcQzmJXpLSXwF8myiiwB234tMIMNAv78i9/+tAAf9skWgXnL16+SMXAkCimsw/F3Frff2iWcpopM1x6oefKyiE2HiRIPoCXl8QxnQY+5X3zW3i1+Zk3GGXKQ8Bm922PxgB/XlPTZQbXG0K/HH3A24h/eJvg2AODkfoo5U5Ehizk56rU6EQAW01U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
